# setup environment
dist: focal
language: java

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
  - APM_TEST_PACKAGES='language-groovy'
  - ATOM_LINT_WITH_BUNDLED_NODE='true'

os: linux
jdk: openjdk11

# execute tests; utilizes public jenkinsci server
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
