// bad environment
// environment section syntax error, and also triggers multiple issues so helpful for future feature
pipeline {
  agent any
  environment {
    bar 'baz'
  }
  stages {
    stage('Info') {
      steps {
        print 'Hello World'
      }
    }
  }
}
